services:
  web:
    build: .
    ports:
      - "${LISTEN_PORT:-8082}:80"
    environment:
      - PORT=80
      - POSTMARK_TOKEN=${POSTMARK_TOKEN}
      - FROM_EMAIL=${FROM_EMAIL:-noreply@traverhardwoodfloors.com}
      - TO_EMAIL=${TO_EMAIL:-chris@traverhardwoodfloors.com}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN:-https://www.traverhardwoodfloors.com}
      - TURNSTILE_SECRET=${TURNSTILE_SECRET}
    restart: unless-stopped
