baseURL = 'https://www.traverhardwoodfloors.com/'
languageCode = 'en-us'
title = 'Traver Hardwood Floors'

[params]
  description = 'Expert hardwood floor installation, refinishing & restoration in Helena, Butte & Bozeman. 6th generation Montana craftsman. Free estimates.'
  tagline = '18 Years. Montana Roots. Your Floors.'
  turnstileSiteKey = '0x4AAAAAACHajsaw-K1k5996'
  phone = '406-451-2282'
  phoneFormatted = '(406) 451-2282'
  phoneTel = '+1-406-451-2282'
  location = 'Helena, Montana'

  [params.social]
    facebook = 'https://www.facebook.com/traverhardwoodfloors'
    instagram = 'https://www.instagram.com/traverhardwoodfloors'
    nextdoor = 'https://nextdoor.com/pages/traver-hardwood-floors-helena-mt'
    google = 'https://www.google.com/maps/place/Traver+Hardwood+Floors/@46.1302274,-112.193272,9z/'

[menu]
  [[menu.main]]
    name = 'Services'
    url = '/services/'
    weight = 1
  [[menu.main]]
    name = 'Our Work'
    url = '/projects/'
    weight = 2
  [[menu.main]]
    name = 'About Us'
    url = '/about-us/'
    weight = 3
  [[menu.main]]
    name = 'Contact Us'
    url = '/contact-us/'
    weight = 4

  [[menu.services]]
    name = 'Installation'
    url = '/installation/'
    weight = 1
  [[menu.services]]
    name = 'Sanding & Finishing'
    url = '/sanding-and-finishing/'
    weight = 2
  [[menu.services]]
    name = 'Repair & Restoration'
    url = '/repair-and-restoration/'
    weight = 3
  [[menu.services]]
    name = 'Stairs'
    url = '/stairs/'
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
